# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created: Thu Dec 27 09:11:55 2012
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(639, 549)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(570, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grouphorizontallayout = QtGui.QHBoxLayout()
        self.grouphorizontallayout.setObjectName(_fromUtf8("grouphorizontallayout"))
        self.groupallbtn = QtGui.QPushButton(self.centralwidget)
        self.groupallbtn.setMinimumSize(QtCore.QSize(0, 0))
        self.groupallbtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.groupallbtn.setObjectName(_fromUtf8("groupallbtn"))
        self.grouphorizontallayout.addWidget(self.groupallbtn)
        self.groupfilterbtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupfilterbtn.sizePolicy().hasHeightForWidth())
        self.groupfilterbtn.setSizePolicy(sizePolicy)
        self.groupfilterbtn.setMinimumSize(QtCore.QSize(25, 0))
        self.groupfilterbtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.groupfilterbtn.setCheckable(True)
        self.groupfilterbtn.setChecked(False)
        self.groupfilterbtn.setFlat(False)
        self.groupfilterbtn.setObjectName(_fromUtf8("groupfilterbtn"))
        self.grouphorizontallayout.addWidget(self.groupfilterbtn)
        self.groupfilterline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupfilterline.sizePolicy().hasHeightForWidth())
        self.groupfilterline.setSizePolicy(sizePolicy)
        self.groupfilterline.setMinimumSize(QtCore.QSize(50, 0))
        self.groupfilterline.setFrame(True)
        self.groupfilterline.setObjectName(_fromUtf8("groupfilterline"))
        self.grouphorizontallayout.addWidget(self.groupfilterline)
        self.groupbox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox.sizePolicy().hasHeightForWidth())
        self.groupbox.setSizePolicy(sizePolicy)
        self.groupbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.grouphorizontallayout.addWidget(self.groupbox)
        self.groupfavouritebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupfavouritebtn.sizePolicy().hasHeightForWidth())
        self.groupfavouritebtn.setSizePolicy(sizePolicy)
        self.groupfavouritebtn.setMinimumSize(QtCore.QSize(0, 0))
        self.groupfavouritebtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.groupfavouritebtn.setObjectName(_fromUtf8("groupfavouritebtn"))
        self.grouphorizontallayout.addWidget(self.groupfavouritebtn)
        self.grouprenamebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grouprenamebtn.sizePolicy().hasHeightForWidth())
        self.grouprenamebtn.setSizePolicy(sizePolicy)
        self.grouprenamebtn.setMinimumSize(QtCore.QSize(0, 0))
        self.grouprenamebtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.grouprenamebtn.setObjectName(_fromUtf8("grouprenamebtn"))
        self.grouphorizontallayout.addWidget(self.grouprenamebtn)
        self.groupdeletebtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupdeletebtn.sizePolicy().hasHeightForWidth())
        self.groupdeletebtn.setSizePolicy(sizePolicy)
        self.groupdeletebtn.setMinimumSize(QtCore.QSize(0, 0))
        self.groupdeletebtn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.groupdeletebtn.setObjectName(_fromUtf8("groupdeletebtn"))
        self.grouphorizontallayout.addWidget(self.groupdeletebtn)
        self.groupnewbtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupnewbtn.sizePolicy().hasHeightForWidth())
        self.groupnewbtn.setSizePolicy(sizePolicy)
        self.groupnewbtn.setMinimumSize(QtCore.QSize(0, 0))
        self.groupnewbtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.groupnewbtn.setObjectName(_fromUtf8("groupnewbtn"))
        self.grouphorizontallayout.addWidget(self.groupnewbtn)
        self.verticalLayout_2.addLayout(self.grouphorizontallayout)
        self.filterhorizontallayout = QtGui.QHBoxLayout()
        self.filterhorizontallayout.setObjectName(_fromUtf8("filterhorizontallayout"))
        self.filterlbl = QtGui.QLabel(self.centralwidget)
        self.filterlbl.setObjectName(_fromUtf8("filterlbl"))
        self.filterhorizontallayout.addWidget(self.filterlbl)
        self.filterreset = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterreset.sizePolicy().hasHeightForWidth())
        self.filterreset.setSizePolicy(sizePolicy)
        self.filterreset.setMinimumSize(QtCore.QSize(0, 0))
        self.filterreset.setMaximumSize(QtCore.QSize(25, 16777215))
        self.filterreset.setObjectName(_fromUtf8("filterreset"))
        self.filterhorizontallayout.addWidget(self.filterreset)
        self.filterrecall = QtGui.QPushButton(self.centralwidget)
        self.filterrecall.setEnabled(False)
        self.filterrecall.setMaximumSize(QtCore.QSize(50, 16777215))
        self.filterrecall.setObjectName(_fromUtf8("filterrecall"))
        self.filterhorizontallayout.addWidget(self.filterrecall)
        self.filterline = QtGui.QLineEdit(self.centralwidget)
        self.filterline.setObjectName(_fromUtf8("filterline"))
        self.filterhorizontallayout.addWidget(self.filterline)
        self.verticalLayout_2.addLayout(self.filterhorizontallayout)
        self.trackstable = QtGui.QTableView(self.centralwidget)
        self.trackstable.setAlternatingRowColors(True)
        self.trackstable.setShowGrid(False)
        self.trackstable.setWordWrap(False)
        self.trackstable.setObjectName(_fromUtf8("trackstable"))
        self.trackstable.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.trackstable)
        self.pagehorizontallayout = QtGui.QHBoxLayout()
        self.pagehorizontallayout.setObjectName(_fromUtf8("pagehorizontallayout"))
        self.pagetrackslbl = QtGui.QLabel(self.centralwidget)
        self.pagetrackslbl.setObjectName(_fromUtf8("pagetrackslbl"))
        self.pagehorizontallayout.addWidget(self.pagetrackslbl)
        self.pagemaxtracksline = QtGui.QLineEdit(self.centralwidget)
        self.pagemaxtracksline.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pagemaxtracksline.setObjectName(_fromUtf8("pagemaxtracksline"))
        self.pagehorizontallayout.addWidget(self.pagemaxtracksline)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.pagehorizontallayout.addItem(spacerItem)
        self.pagepagelbl = QtGui.QLabel(self.centralwidget)
        self.pagepagelbl.setObjectName(_fromUtf8("pagepagelbl"))
        self.pagehorizontallayout.addWidget(self.pagepagelbl)
        self.pageprevbtn = QtGui.QPushButton(self.centralwidget)
        self.pageprevbtn.setObjectName(_fromUtf8("pageprevbtn"))
        self.pagehorizontallayout.addWidget(self.pageprevbtn)
        self.pagepageline = QtGui.QLineEdit(self.centralwidget)
        self.pagepageline.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pagepageline.setObjectName(_fromUtf8("pagepageline"))
        self.pagehorizontallayout.addWidget(self.pagepageline)
        self.pagemaxpagelbl = QtGui.QLabel(self.centralwidget)
        self.pagemaxpagelbl.setObjectName(_fromUtf8("pagemaxpagelbl"))
        self.pagehorizontallayout.addWidget(self.pagemaxpagelbl)
        self.pagenextbtn = QtGui.QPushButton(self.centralwidget)
        self.pagenextbtn.setObjectName(_fromUtf8("pagenextbtn"))
        self.pagehorizontallayout.addWidget(self.pagenextbtn)
        self.verticalLayout_2.addLayout(self.pagehorizontallayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTrack = QtGui.QMenu(self.menubar)
        self.menuTrack.setObjectName(_fromUtf8("menuTrack"))
        self.menuTrackAddToGroup = QtGui.QMenu(self.menuTrack)
        self.menuTrackAddToGroup.setObjectName(_fromUtf8("menuTrackAddToGroup"))
        self.menuTrackMerge = QtGui.QMenu(self.menuTrack)
        self.menuTrackMerge.setObjectName(_fromUtf8("menuTrackMerge"))
        self.menuTrackInGroups = QtGui.QMenu(self.menuTrack)
        self.menuTrackInGroups.setObjectName(_fromUtf8("menuTrackInGroups"))
        self.menuRating = QtGui.QMenu(self.menuTrack)
        self.menuRating.setObjectName(_fromUtf8("menuRating"))
        self.menuTrackRelink = QtGui.QMenu(self.menuTrack)
        self.menuTrackRelink.setObjectName(_fromUtf8("menuTrackRelink"))
        self.menuGroup = QtGui.QMenu(self.menubar)
        self.menuGroup.setObjectName(_fromUtf8("menuGroup"))
        self.menuGroupNewImport = QtGui.QMenu(self.menuGroup)
        self.menuGroupNewImport.setObjectName(_fromUtf8("menuGroupNewImport"))
        self.menuPage = QtGui.QMenu(self.menubar)
        self.menuPage.setObjectName(_fromUtf8("menuPage"))
        self.menuFilter = QtGui.QMenu(self.menubar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuFilterHistory = QtGui.QMenu(self.menuFilter)
        self.menuFilterHistory.setObjectName(_fromUtf8("menuFilterHistory"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTrackNew = QtGui.QAction(MainWindow)
        self.actionTrackNew.setObjectName(_fromUtf8("actionTrackNew"))
        self.actionTrackDelete = QtGui.QAction(MainWindow)
        self.actionTrackDelete.setObjectName(_fromUtf8("actionTrackDelete"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionGroupAllTracks = QtGui.QAction(MainWindow)
        self.actionGroupAllTracks.setObjectName(_fromUtf8("actionGroupAllTracks"))
        self.actionGroupFavourite = QtGui.QAction(MainWindow)
        self.actionGroupFavourite.setObjectName(_fromUtf8("actionGroupFavourite"))
        self.actionGroupDelete = QtGui.QAction(MainWindow)
        self.actionGroupDelete.setObjectName(_fromUtf8("actionGroupDelete"))
        self.actionPageNext = QtGui.QAction(MainWindow)
        self.actionPageNext.setObjectName(_fromUtf8("actionPageNext"))
        self.actionPagePrev = QtGui.QAction(MainWindow)
        self.actionPagePrev.setObjectName(_fromUtf8("actionPagePrev"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionGroupRename = QtGui.QAction(MainWindow)
        self.actionGroupRename.setObjectName(_fromUtf8("actionGroupRename"))
        self.actionGroupNew = QtGui.QAction(MainWindow)
        self.actionGroupNew.setObjectName(_fromUtf8("actionGroupNew"))
        self.actionGroupImportCue = QtGui.QAction(MainWindow)
        self.actionGroupImportCue.setObjectName(_fromUtf8("actionGroupImportCue"))
        self.actionGroupImportDirectory = QtGui.QAction(MainWindow)
        self.actionGroupImportDirectory.setObjectName(_fromUtf8("actionGroupImportDirectory"))
        self.actionTrackToGroup = QtGui.QAction(MainWindow)
        self.actionTrackToGroup.setObjectName(_fromUtf8("actionTrackToGroup"))
        self.actionTrackToggleNew = QtGui.QAction(MainWindow)
        self.actionTrackToggleNew.setObjectName(_fromUtf8("actionTrackToggleNew"))
        self.actionFilterReset = QtGui.QAction(MainWindow)
        self.actionFilterReset.setObjectName(_fromUtf8("actionFilterReset"))
        self.actionFilterPlaceholder = QtGui.QAction(MainWindow)
        self.actionFilterPlaceholder.setObjectName(_fromUtf8("actionFilterPlaceholder"))
        self.actionTrackDetachedCopy = QtGui.QAction(MainWindow)
        self.actionTrackDetachedCopy.setObjectName(_fromUtf8("actionTrackDetachedCopy"))
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTrackAddToGroup.addSeparator()
        self.menuTrackMerge.addSeparator()
        self.menuTrackInGroups.addSeparator()
        self.menuTrack.addAction(self.actionTrackNew)
        self.menuTrack.addAction(self.actionTrackDelete)
        self.menuTrack.addSeparator()
        self.menuTrack.addAction(self.menuTrackMerge.menuAction())
        self.menuTrack.addAction(self.menuTrackAddToGroup.menuAction())
        self.menuTrack.addAction(self.menuTrackInGroups.menuAction())
        self.menuTrack.addAction(self.actionTrackDetachedCopy)
        self.menuTrack.addAction(self.menuTrackRelink.menuAction())
        self.menuTrack.addSeparator()
        self.menuTrack.addAction(self.menuRating.menuAction())
        self.menuTrack.addAction(self.actionTrackToggleNew)
        self.menuGroupNewImport.addAction(self.actionGroupNew)
        self.menuGroupNewImport.addAction(self.actionGroupImportCue)
        self.menuGroupNewImport.addAction(self.actionGroupImportDirectory)
        self.menuGroup.addAction(self.actionGroupAllTracks)
        self.menuGroup.addSeparator()
        self.menuGroup.addAction(self.menuGroupNewImport.menuAction())
        self.menuGroup.addAction(self.actionGroupDelete)
        self.menuGroup.addSeparator()
        self.menuGroup.addAction(self.actionGroupFavourite)
        self.menuGroup.addAction(self.actionGroupRename)
        self.menuPage.addAction(self.actionPageNext)
        self.menuPage.addAction(self.actionPagePrev)
        self.menuFilterHistory.addAction(self.actionFilterPlaceholder)
        self.menuFilter.addAction(self.actionFilterReset)
        self.menuFilter.addAction(self.menuFilterHistory.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTrack.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuGroup.menuAction())
        self.menubar.addAction(self.menuPage.menuAction())
        self.filterlbl.setBuddy(self.filterline)
        self.pagetrackslbl.setBuddy(self.pagemaxtracksline)
        self.pagepagelbl.setBuddy(self.pagepageline)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "regaudio", None))
        self.groupallbtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>all tracks</p><p>(click again to return to the previous group)</p></body></html>", None))
        self.groupallbtn.setText(_translate("MainWindow", "|||", None))
        self.groupfilterbtn.setToolTip(_translate("MainWindow", "filter groups", None))
        self.groupfilterbtn.setText(_translate("MainWindow", "?", None))
        self.groupfilterline.setToolTip(_translate("MainWindow", "you may use wildcards (*, ?)", None))
        self.groupfavouritebtn.setToolTip(_translate("MainWindow", "toggle favorite", None))
        self.groupfavouritebtn.setText(_translate("MainWindow", "*", None))
        self.grouprenamebtn.setToolTip(_translate("MainWindow", "rename group", None))
        self.grouprenamebtn.setText(_translate("MainWindow", "R", None))
        self.groupdeletebtn.setToolTip(_translate("MainWindow", "remove group (but keep tracks)", None))
        self.groupdeletebtn.setText(_translate("MainWindow", "-", None))
        self.groupnewbtn.setToolTip(_translate("MainWindow", "add a group", None))
        self.groupnewbtn.setText(_translate("MainWindow", "+", None))
        self.filterlbl.setText(_translate("MainWindow", "Filter", None))
        self.filterreset.setToolTip(_translate("MainWindow", "reset filter", None))
        self.filterreset.setText(_translate("MainWindow", "x", None))
        self.filterrecall.setToolTip(_translate("MainWindow", "recall previous filter", None))
        self.filterrecall.setText(_translate("MainWindow", "~", None))
        self.filterline.setToolTip(_translate("MainWindow", "<html><head/><body><p>two types of filter are recognized:</p><p>- a simple filter (all the fields are searched)</p><p>- an advanced filter (!a: for artist, !n: for name, !r: for rating, !r:&lt; lower rating, !r:&gt; higher rating, !*: new, !g:group) eg.:!a:Frank Sinatra !n:my way</p><p>filter is always case insensitive</p></body></html>", None))
        self.pagetrackslbl.setText(_translate("MainWindow", "Tracks per page", None))
        self.pagemaxtracksline.setText(_translate("MainWindow", "200", None))
        self.pagepagelbl.setText(_translate("MainWindow", "Page", None))
        self.pageprevbtn.setText(_translate("MainWindow", "< Prev", None))
        self.pagepageline.setText(_translate("MainWindow", "1", None))
        self.pagemaxpagelbl.setText(_translate("MainWindow", "/ 1", None))
        self.pagenextbtn.setText(_translate("MainWindow", "Next >", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuTrack.setTitle(_translate("MainWindow", "&Track", None))
        self.menuTrackAddToGroup.setTitle(_translate("MainWindow", "&Add to group", None))
        self.menuTrackMerge.setTitle(_translate("MainWindow", "&Merge as", None))
        self.menuTrackInGroups.setTitle(_translate("MainWindow", "&In groups", None))
        self.menuRating.setTitle(_translate("MainWindow", "&Rating", None))
        self.menuTrackRelink.setTitle(_translate("MainWindow", "Relink as &similar", None))
        self.menuGroup.setTitle(_translate("MainWindow", "&Group", None))
        self.menuGroupNewImport.setTitle(_translate("MainWindow", "&New group", None))
        self.menuPage.setTitle(_translate("MainWindow", "&Page", None))
        self.menuFilter.setTitle(_translate("MainWindow", "&Filter", None))
        self.menuFilterHistory.setTitle(_translate("MainWindow", "&History", None))
        self.actionTrackNew.setText(_translate("MainWindow", "&New entry", None))
        self.actionTrackNew.setToolTip(_translate("MainWindow", "Add new track and edit it", None))
        self.actionTrackNew.setShortcut(_translate("MainWindow", "N", None))
        self.actionTrackDelete.setText(_translate("MainWindow", "&Delete", None))
        self.actionTrackDelete.setShortcut(_translate("MainWindow", "Del", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionGroupAllTracks.setText(_translate("MainWindow", "&All tracks", None))
        self.actionGroupFavourite.setText(_translate("MainWindow", "Toggle &favourite", None))
        self.actionGroupDelete.setText(_translate("MainWindow", "&Delete group", None))
        self.actionPageNext.setText(_translate("MainWindow", "&Next", None))
        self.actionPageNext.setToolTip(_translate("MainWindow", "Next Page", None))
        self.actionPagePrev.setText(_translate("MainWindow", "&Prev", None))
        self.actionImport.setText(_translate("MainWindow", "&Import", None))
        self.actionGroupRename.setText(_translate("MainWindow", "R&ename", None))
        self.actionGroupNew.setText(_translate("MainWindow", "&Add empty group", None))
        self.actionGroupImportCue.setText(_translate("MainWindow", "Import .&cue", None))
        self.actionGroupImportDirectory.setText(_translate("MainWindow", "Import &directory", None))
        self.actionTrackToGroup.setText(_translate("MainWindow", "Pick from all ...", None))
        self.actionTrackToggleNew.setText(_translate("MainWindow", "&Toggle New", None))
        self.actionTrackToggleNew.setShortcut(_translate("MainWindow", ".", None))
        self.actionFilterReset.setText(_translate("MainWindow", "&Reset", None))
        self.actionFilterReset.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionFilterPlaceholder.setText(_translate("MainWindow", "placeholder", None))
        self.actionTrackDetachedCopy.setText(_translate("MainWindow", "Detached &copy", None))
        self.actionTrackDetachedCopy.setToolTip(_translate("MainWindow", "<html><head/><body><p>make a copy of the track and point the grouptrack to it</p><p>(only in groups)</p></body></html>", None))

